/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Files.readAdmin;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yibei
 */
public class admin_password extends javax.swing.JFrame {

    /**
     * Creates new form admin_password
     */
    String username; 
    
    public admin_password() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }
    
    public admin_password(String username) {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordPF = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();
        returnBT = new javax.swing.JButton();
        confirmBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        passwordPF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(passwordPF);
        passwordPF.setBounds(300, 320, 390, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/admin_change_password.png"))); // NOI18N
        background.setText("jLabel2");
        background.setMaximumSize(new java.awt.Dimension(1366, 768));
        background.setMinimumSize(new java.awt.Dimension(1366, 768));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(background);
        background.setBounds(0, -10, 1370, 790);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(20, 10, 150, 90);

        confirmBT.setText("jButton1");
        confirmBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTActionPerformed(evt);
            }
        });
        getContentPane().add(confirmBT);
        confirmBT.setBounds(310, 450, 270, 80);

        logoutBT.setText("jButton1");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBT);
        logoutBT.setBounds(1190, 20, 150, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        // TODO add your handling code here:
        new admin_profile(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        Startpage startPage = new Startpage();
        startPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTActionPerformed


    private void confirmBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTActionPerformed
        // TODO add your handling code here:
        FileReader fr;
        
        // temporary array used to hold data that is read from file
        ArrayList<String> tempArray = new ArrayList<>();
        String newpass = passwordPF.getText();
        ArrayList<Admin> list;
        try {
            list = readAdmin();
            for(Admin a : list) {
            if(a.getUsername().equals(this.username))
                tempArray.add(this.username + "," + newpass);
            else
                tempArray.add(a.toString());
        }
        } catch (IOException ex) {
            Logger.getLogger(admin_password.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //write the data in temp array(edited data) into file
        try(PrintWriter pr = new PrintWriter("admin.txt")) {
            for (String str : tempArray) {
                pr.println(str);
            }
            pr.close();
            JOptionPane.showMessageDialog(null, "PASSWORD CHANGED~");
            passwordPF.setText(null);
            new admin_profile(this.username).setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(admin_password.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void admin_password(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton confirmBT;
    private javax.swing.JButton logoutBT;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JButton returnBT;
    // End of variables declaration//GEN-END:variables
}
