/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Files.editBooking;
import static GUI.Files.readBooking;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yibei
 */
public class car_status extends javax.swing.JFrame {

    /**
     * Creates new form car_status
     */
    String username;
    String cusUsername;
    String carPlate;

    public car_status() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    public car_status(String username) throws IOException {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
        table.setAutoCreateRowSorter(true);
        displayTable();
    }

    public void displayTable() throws IOException {
        ArrayList<Booking> list = readBooking();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (Booking b : list) {
            if (!(b.getPaymentStatus().equals("nopayment"))) {
                String line = b.getUsername() + "," + b.getCarID() + "," + b.getCarBrand() + "," + b.getCarName() + "," + b.getLocation() + ","
                        + b.getPickupDate() + "," + b.getPickupTime() + "," + b.getDropoffDate() + "," + b.getDropoffTime() + ","
                        + b.getCarStatus() + "," + b.getCarPlate();
                String[] carStatus = line.split(",");
                model.addRow(carStatus);
            }
        }
    }

    //to change the status of the car
    public void changeStatus(int s) {
        String status = null;
        switch (s) {
            case 1:
                status = "pickup";
                break;
            case 2:
                status = "returned";
                break;
            case 3:
                status = "nopickup";
                break;
        }
        ArrayList<String> tempArray = new ArrayList<>();
        try {
            ArrayList<Booking> list = readBooking();
            for (Booking b : list) {
                if (b.getUsername().equals(this.cusUsername) && b.getCarPlate().equals(this.carPlate)) {
                    b.setCarStatus(status);
                    tempArray.add(b.toString());
                } else {
                    tempArray.add(b.toString());
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(car_status.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            editBooking(tempArray,"cusbooking.txt");
            displayTable();
        } catch (IOException ex) {
            Logger.getLogger(car_status.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        usernameTF = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        returnBT = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();
        pickupBT = new javax.swing.JButton();
        returnedBT = new javax.swing.JButton();
        nopickupBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "CarID", "Brand", "Name", "Location", "Pickup Date", "Pickup Time", "Dropoff Date", "Dropoff Time", "Car Status", "Car Plate"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 422, 1130, 330);

        usernameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usernameTF.setBorder(null);
        getContentPane().add(usernameTF);
        usernameTF.setBounds(190, 180, 320, 40);

        dateTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dateTF.setBorder(null);
        getContentPane().add(dateTF);
        dateTF.setBounds(190, 280, 320, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/car_status.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1366, 768));
        background.setMinimumSize(new java.awt.Dimension(1366, 768));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(background);
        background.setBounds(0, -30, 1366, 820);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(20, 20, 130, 60);

        searchBT.setText("jButton1");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        getContentPane().add(searchBT);
        searchBT.setBounds(280, 350, 130, 50);

        pickupBT.setText("jButton1");
        pickupBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupBTActionPerformed(evt);
            }
        });
        getContentPane().add(pickupBT);
        pickupBT.setBounds(1200, 450, 130, 50);

        returnedBT.setText("jButton1");
        returnedBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnedBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnedBT);
        returnedBT.setBounds(1200, 560, 130, 50);

        nopickupBT.setText("jButton1");
        nopickupBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopickupBTActionPerformed(evt);
            }
        });
        getContentPane().add(nopickupBT);
        nopickupBT.setBounds(1200, 660, 130, 60);

        logoutBT.setText("jButton1");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBT);
        logoutBT.setBounds(1190, 10, 150, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();
        this.cusUsername = model.getValueAt(row, 0).toString();
        this.carPlate = model.getValueAt(row, 10).toString();
    }//GEN-LAST:event_tableMouseClicked

    private void pickupBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupBTActionPerformed
        // change status to pick up
        changeStatus(1);
    }//GEN-LAST:event_pickupBTActionPerformed

    private void returnedBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnedBTActionPerformed
        //change status to returned
        changeStatus(2);
    }//GEN-LAST:event_returnedBTActionPerformed

    private void nopickupBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopickupBTActionPerformed
        //change status to no pick up
        changeStatus(3);
    }//GEN-LAST:event_nopickupBTActionPerformed

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        // TODO add your handling code here:
        new Adminpage(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBTActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        //search data based on username or pick up date
        try {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            String name = usernameTF.getText();
            String date = dateTF.getText();
            ArrayList<Booking> list = readBooking();
            for (Booking b : list) {
                if (!(b.getPaymentStatus().equals("nopayment"))) {
                    if (b.getUsername().equals(name) | b.getPickupDate().equals(date)) {
                        String line = b.getUsername() + "," + b.getCarID() + "," + b.getCarBrand() + "," + b.getCarName() + "," + b.getLocation() + ","
                                + b.getPickupDate() + "," + b.getPickupTime() + "," + b.getDropoffDate() + "," + b.getDropoffTime() + ","
                                + b.getCarStatus() + "," + b.getCarPlate();
                        String[] carStatus = line.split(",");
                        model.addRow(carStatus);
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(car_status.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void car_status(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(car_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(car_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(car_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(car_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new car_status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField dateTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBT;
    private javax.swing.JButton nopickupBT;
    private javax.swing.JButton pickupBT;
    private javax.swing.JButton returnBT;
    private javax.swing.JButton returnedBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JTable table;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
