/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Files.readCustomer;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yibei
 */
public class create_acc extends javax.swing.JFrame {

    String username;

    /**
     * Creates new form create_acc
     */
    public create_acc() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressTF = new javax.swing.JTextField();
        firstnameTF = new javax.swing.JTextField();
        lastnameTF = new javax.swing.JTextField();
        usernameTF = new javax.swing.JTextField();
        contactTF = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        loginBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        addressTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });
        getContentPane().add(addressTF);
        addressTF.setBounds(660, 440, 460, 40);

        firstnameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(firstnameTF);
        firstnameTF.setBounds(660, 160, 460, 40);

        lastnameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lastnameTF);
        lastnameTF.setBounds(660, 230, 460, 40);

        usernameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTF);
        usernameTF.setBounds(660, 300, 460, 40);

        contactTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTFActionPerformed(evt);
            }
        });
        contactTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTFKeyTyped(evt);
            }
        });
        getContentPane().add(contactTF);
        contactTF.setBounds(660, 370, 460, 40);

        password1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(password1);
        password1.setBounds(660, 580, 460, 40);

        password2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(password2);
        password2.setBounds(660, 510, 460, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/create_acc.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 780);

        backBT.setText("jButton1");
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        getContentPane().add(backBT);
        backBT.setBounds(1240, 40, 100, 40);

        loginBT.setText("jButton1");
        loginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTActionPerformed(evt);
            }
        });
        getContentPane().add(loginBT);
        loginBT.setBounds(610, 670, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearTF() {   //clear all the text fields
        firstnameTF.setText(null);
        lastnameTF.setText(null);
        usernameTF.setText(null);
        contactTF.setText(null);
        addressTF.setText(null);
        password1.setText(null);
        password1.setText(null);
    }

    private void loginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTActionPerformed
        // register as member
        String firstName = firstnameTF.getText();
        String lastName = lastnameTF.getText();
        String userName = usernameTF.getText();
        String contactNumber = contactTF.getText();
        String address = addressTF.getText();
        String password = password1.getText();
        String passwordConfirm = password2.getText();

        int repeat = 0;
        try {
            ArrayList<Customer> list = readCustomer();
            for (Customer c : list) {
                if (c.getUsername().equals(userName)) {
                    repeat = 1;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(create_acc.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (firstName.isEmpty() || lastName.isEmpty() || userName.isEmpty() || contactNumber.isEmpty() || address.isEmpty() || password.isEmpty() || passwordConfirm.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up all details");
        } else if (repeat == 1) {
            JOptionPane.showMessageDialog(null, "Username not available");
            usernameTF.setText(null);
        } else {
            if (!(password.equals(passwordConfirm))) {
                JOptionPane.showMessageDialog(null, "Password not match");
                password1.setText(null);
                password2.setText(null);
            } else {
                try {
                    FileWriter writer = new FileWriter("customerinfo.txt", true);
                    writer.write(firstName + "," + lastName + "," + userName + "," + contactNumber + "," + address + "," + password);
                    writer.write(System.getProperty("line.separator"));
                    writer.close();
                    FileWriter fw = new FileWriter("newmembers.txt", true);
                    fw.write(firstName + "," + lastName + "," + userName + "," + contactNumber + "," + address + "," + password + ","
                            + java.time.LocalDate.now() + "," + java.time.LocalTime.now());
                    fw.write(System.getProperty("line.separator"));
                    fw.close();
                    this.username = userName;
                    this.setVisible(false);
                    new Customerpage(this.username).setVisible(true);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Register failed, please try again.");
                    clearTF();
                }
            }
        }
    }//GEN-LAST:event_loginBTActionPerformed

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void contactTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTFActionPerformed

    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTFActionPerformed

    private void contactTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTFKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Invalid Contact Number!!!");
            evt.consume();
            contactTF.setText(null);
        }
    }//GEN-LAST:event_contactTFKeyTyped

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void create_acc() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_acc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton backBT;
    private javax.swing.JTextField contactTF;
    private javax.swing.JTextField firstnameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lastnameTF;
    private javax.swing.JButton loginBT;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
