/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Files.editBooking;
import static GUI.Files.readCustomer;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yibei
 */
public class cus_edit_profile extends javax.swing.JFrame {

    /**
     * Creates new form cus_edit_profile
     */
    String username;

    public cus_edit_profile() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    public cus_edit_profile(String username) throws IOException {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
        displaydetails();
    }

    public void displaydetails() throws IOException {
        ArrayList<Customer> list = readCustomer();
        for (Customer c : list) {
            if (c.getUsername().equals(this.username)) {
                firstnameTF.setText(c.getFirstName());
                lastnameTF.setText(c.getLastName());
                addressTF.setText(c.getAddress());
                contactTF.setText(c.getContactNo());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contactTF = new javax.swing.JTextField();
        lastnameTF = new javax.swing.JTextField();
        firstnameTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        returnBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("Contact No:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 490, 170, 80);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 330, 170, 80);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 250, 170, 80);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel4.setText("Address:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 410, 170, 80);

        contactTF.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        contactTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTFActionPerformed(evt);
            }
        });
        contactTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTFKeyTyped(evt);
            }
        });
        getContentPane().add(contactTF);
        contactTF.setBounds(340, 510, 360, 50);

        lastnameTF.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lastnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTFActionPerformed(evt);
            }
        });
        getContentPane().add(lastnameTF);
        lastnameTF.setBounds(340, 350, 360, 50);

        firstnameTF.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        firstnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTFActionPerformed(evt);
            }
        });
        getContentPane().add(firstnameTF);
        firstnameTF.setBounds(340, 270, 360, 50);

        addressTF.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });
        getContentPane().add(addressTF);
        addressTF.setBounds(340, 430, 360, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/cus_edit_profile.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1338, 768));
        background.setMinimumSize(new java.awt.Dimension(1338, 768));
        background.setPreferredSize(new java.awt.Dimension(1338, 768));
        getContentPane().add(background);
        background.setBounds(0, -20, 1370, 820);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(30, 30, 180, 70);

        logoutBT.setText("jButton1");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBT);
        logoutBT.setBounds(1210, 20, 110, 80);

        editBT.setText("jButton1");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });
        getContentPane().add(editBT);
        editBT.setBounds(350, 650, 130, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTFActionPerformed

    private void lastnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTFActionPerformed

    private void contactTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTFActionPerformed

    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTFActionPerformed

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        try {
            // TODO add your handling code here:
            new cus_profile(this.username).setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(cus_edit_profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_returnBTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        //edit profile
        try {
            String firstName = firstnameTF.getText();
            String lastName = lastnameTF.getText();
            String address = addressTF.getText();
            String conNum = contactTF.getText();
            ArrayList<String> tempArray = new ArrayList<>();
            ArrayList<Customer> list = readCustomer();
            for (Customer c : list) {
                if (c.getUsername().equals(this.username)) {
                    c.setFirstName(firstName);
                    c.setLastName(lastName);
                    c.setAddress(address);
                    c.setContactNo(conNum);
                    tempArray.add(c.toString());
                } else {
                    tempArray.add(c.toString());
                }
            }
            editBooking(tempArray, "customerinfo.txt");
            JOptionPane.showMessageDialog(null, "EDITED~");
            this.setVisible(false);
            new cus_profile(this.username).setVisible(true);
            displaydetails();
        } catch (IOException ex) {
            Logger.getLogger(cus_edit_profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editBTActionPerformed

    private void contactTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTFKeyTyped
        // validation
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Invalid Contact Number!!!");
            evt.consume();
            contactTF.setText(null);
        }
    }//GEN-LAST:event_contactTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void cus_edit_profile(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cus_edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cus_edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cus_edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cus_edit_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cus_edit_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.JLabel background;
    private javax.swing.JTextField contactTF;
    private javax.swing.JButton editBT;
    private javax.swing.JTextField firstnameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lastnameTF;
    private javax.swing.JButton logoutBT;
    private javax.swing.JButton returnBT;
    // End of variables declaration//GEN-END:variables
}
