/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Files.displayCars;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yibei
 */
public class edit_car extends javax.swing.JFrame {

    String username;

    /**
     * Creates new form edit_car
     */
    public edit_car() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    public edit_car(String username) throws FileNotFoundException {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
        table.setAutoCreateRowSorter(true);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        ArrayList<cars> list = displayCars();
        for (cars c : list) {
            model.addRow(c.toString().split(","));
        }
    }

    
    //copy the whole time into file
    private static void updateFile(DefaultTableModel model) {
        try {
            FileWriter fw = new FileWriter("carinfo.txt");

            for (int row = 0; row < model.getRowCount(); row++) {
                for (int col = 0; col < model.getColumnCount(); col++) {
                    fw.write(model.getValueAt(row, col) + ",");
                }
                fw.write("\r\n");
            }

            fw.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        priceTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        brandTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        numberTF = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        returnBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        deleteBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setBackground(new java.awt.Color(129, 163, 163));
        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BRAND", "NAME", "PRICE", "NUMBER"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(750, 170, 580, 460);

        priceTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });
        getContentPane().add(priceTF);
        priceTF.setBounds(360, 430, 310, 40);

        idTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(idTF);
        idTF.setBounds(360, 210, 310, 40);

        brandTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(brandTF);
        brandTF.setBounds(360, 280, 310, 40);

        nameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(nameTF);
        nameTF.setBounds(360, 350, 310, 40);

        numberTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(numberTF);
        numberTF.setBounds(360, 500, 310, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/edit_car.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1366, 768));
        background.setMinimumSize(new java.awt.Dimension(1366, 768));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(background);
        background.setBounds(0, 0, 1790, 770);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(20, 30, 140, 70);

        editBT.setText("jButton1");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });
        getContentPane().add(editBT);
        editBT.setBounds(510, 660, 160, 70);

        deleteBT.setText("jButton1");
        deleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBT);
        deleteBT.setBounds(720, 660, 160, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearTF() {
        idTF.setText(null);
        brandTF.setText(null);
        nameTF.setText(null);
        numberTF.setText(null);
        priceTF.setText(null);
    }


    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        // delete row
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        if (table.getSelectedRowCount() == 1) {
            model.removeRow(table.getSelectedRow());
            clearTF();
            updateFile(model);
        } else {
            if (table.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "The Table is empty!!");
            } else {
                JOptionPane.showMessageDialog(this, "Please select single row everytime!!");
            }
        }


    }//GEN-LAST:event_deleteBTActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // when clicked the selected row, textfield will appeared the data
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();
        idTF.setText(model.getValueAt(row, 0).toString());
        brandTF.setText(model.getValueAt(row, 1).toString());
        nameTF.setText(model.getValueAt(row, 2).toString());
        priceTF.setText(model.getValueAt(row, 3).toString());
        numberTF.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        // edit every data
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();
        if (row >= 0) {
            model.setValueAt(idTF.getText(), row, 0);
            model.setValueAt(brandTF.getText(), row, 1);
            model.setValueAt(nameTF.getText(), row, 2);
            model.setValueAt(priceTF.getText(), row, 3);
            model.setValueAt(numberTF.getText(), row, 4);
            clearTF();
            updateFile(model);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row");
        }
    }//GEN-LAST:event_editBTActionPerformed

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        // back to admin menu
        this.setVisible(false);
        new Adminpage(this.username).setVisible(true);
    }//GEN-LAST:event_returnBTActionPerformed

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void edit_car(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField brandTF;
    private javax.swing.JButton deleteBT;
    private javax.swing.JButton editBT;
    private javax.swing.JTextField idTF;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField numberTF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JButton returnBT;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
