/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yibei
 */
public class generate_report extends javax.swing.JFrame {

    /**
     * Creates new form generate_report
     */
    String username;
    
    public generate_report() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }
    
    public generate_report(String username) {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        report_money = new javax.swing.JButton();
        report_memberBT = new javax.swing.JButton();
        report_carrented = new javax.swing.JButton();
        report_caravailable = new javax.swing.JButton();
        returnBT = new javax.swing.JButton();
        report_systemlog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/generate_report.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1366, 768));
        background.setMinimumSize(new java.awt.Dimension(1366, 768));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(background);
        background.setBounds(0, -30, 1380, 840);

        report_money.setText("jButton1");
        report_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_moneyActionPerformed(evt);
            }
        });
        getContentPane().add(report_money);
        report_money.setBounds(650, 330, 200, 220);

        report_memberBT.setText("jButton1");
        report_memberBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_memberBTActionPerformed(evt);
            }
        });
        getContentPane().add(report_memberBT);
        report_memberBT.setBounds(470, 330, 150, 220);

        report_carrented.setText("jButton1");
        report_carrented.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_carrentedActionPerformed(evt);
            }
        });
        getContentPane().add(report_carrented);
        report_carrented.setBounds(40, 350, 400, 190);

        report_caravailable.setText("jButton1");
        report_caravailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_caravailableActionPerformed(evt);
            }
        });
        getContentPane().add(report_caravailable);
        report_caravailable.setBounds(50, 590, 460, 90);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(10, 20, 160, 80);

        report_systemlog.setText("jButton1");
        report_systemlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_systemlogActionPerformed(evt);
            }
        });
        getContentPane().add(report_systemlog);
        report_systemlog.setBounds(550, 590, 320, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void report_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_moneyActionPerformed
        // TODO add your handling code here:
        new report_money(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_report_moneyActionPerformed

    private void report_memberBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_memberBTActionPerformed
        // TODO add your handling code here:
        new report_member(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_report_memberBTActionPerformed

    private void report_carrentedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_carrentedActionPerformed
        try {
            // TODO add your handling code here:
            new report_carrented(this.username).setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(generate_report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_report_carrentedActionPerformed

    private void report_caravailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_caravailableActionPerformed
        try {
            // TODO add your handling code here:
            new report_caravailable(this.username).setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(generate_report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_report_caravailableActionPerformed

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        // TODO add your handling code here:
        new Adminpage(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBTActionPerformed

    private void report_systemlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_systemlogActionPerformed
        // TODO add your handling code here:
        new report_systemlog(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_report_systemlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void generate_report(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generate_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton report_caravailable;
    private javax.swing.JButton report_carrented;
    private javax.swing.JButton report_memberBT;
    private javax.swing.JButton report_money;
    private javax.swing.JButton report_systemlog;
    private javax.swing.JButton returnBT;
    // End of variables declaration//GEN-END:variables
}
