/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yibei
 */
public class report_money extends javax.swing.JFrame {

    /**
     * Creates new form report_money
     */
    String username;

    public report_money() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    public report_money(String username) {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
        table.setAutoCreateRowSorter(true);
        displayTable();
        getTotal();
    }

    public void getTotal() {
        double sum = 0;
        for (int j = 0; j < table.getRowCount(); j++) {
            sum = sum + Double.parseDouble(table.getValueAt(j, 6).toString());
        }
        String totalPrice = String.valueOf(sum);
        total.setText(totalPrice);
    }

    public void displayTable() {
        FileReader file;
        try {
            file = new FileReader("paymenthistory.txt");
            BufferedReader reader = new BufferedReader(file);
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            Object[] tableLines = reader.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] info = line.split(",");
                String paymentInfo = info[9] + "," + info[10] + "," + info[0] + "," + info[1] + "," + info[2] + "," + info[4] + "," + info[5] + "," + info[3];
                String[] tableData = paymentInfo.split(",");
                model.addRow(tableData);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(car_info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        mm = new javax.swing.JLabel();
        yyyy = new javax.swing.JLabel();
        mm1 = new javax.swing.JLabel();
        yearTF = new javax.swing.JTextField();
        monthTF = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        searchBT = new javax.swing.JButton();
        printBT = new javax.swing.JButton();
        returnBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setBackground(new java.awt.Color(0, 102, 102));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PAYMENT DATE", "PAYMENT TIME", "USERNAME", "CarID", "Car Plate", "Card Name", "Card Number", "Price"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 290, 1130, 270);

        total.setFont(new java.awt.Font("Elephant", 0, 48)); // NOI18N
        getContentPane().add(total);
        total.setBounds(250, 570, 280, 70);

        mm.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mm.setText("YYYY");
        getContentPane().add(mm);
        mm.setBounds(510, 250, 40, 20);

        yyyy.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        yyyy.setText("MM");
        getContentPane().add(yyyy);
        yyyy.setBounds(350, 250, 40, 20);

        mm1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mm1.setText("MM");
        getContentPane().add(mm1);
        mm1.setBounds(350, 250, 40, 20);

        yearTF.setFont(new java.awt.Font("Niagara Engraved", 0, 56)); // NOI18N
        yearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTFActionPerformed(evt);
            }
        });
        getContentPane().add(yearTF);
        yearTF.setBounds(400, 200, 100, 70);

        monthTF.setFont(new java.awt.Font("Niagara Engraved", 0, 56)); // NOI18N
        monthTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTFActionPerformed(evt);
            }
        });
        getContentPane().add(monthTF);
        monthTF.setBounds(240, 200, 100, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/report_money.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1366, 768));
        background.setMinimumSize(new java.awt.Dimension(1366, 768));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(background);
        background.setBounds(0, -30, 1370, 830);

        searchBT.setText("jButton1");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        getContentPane().add(searchBT);
        searchBT.setBounds(150, 200, 75, 70);

        printBT.setText("jButton1");
        printBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBTActionPerformed(evt);
            }
        });
        getContentPane().add(printBT);
        printBT.setBounds(630, 630, 140, 60);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(0, 20, 160, 50);

        logoutBT.setText("jButton1");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBT);
        logoutBT.setBounds(1170, 13, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        // TODO add your handling code here:
        String monthFilter = monthTF.getText();
        String yearFilter = yearTF.getText();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        FileReader file;
        model.setRowCount(0);
        try {
            file = new FileReader("paymenthistory.txt");
            BufferedReader reader = new BufferedReader(file);
            Object[] tableLines = reader.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] info = line.split(",");
                String[] paiddate = info[9].split("-");
                if (paiddate[0].equals(yearFilter) && paiddate[1].equals(monthFilter)) {
                    String paymentInfo = info[9] + "," + info[10] + "," + info[0] + "," + info[1] + "," + info[2] + "," + info[4] + "," + info[5] + "," + info[3];
                    String[] tableData = paymentInfo.split(",");
                    model.addRow(tableData);
                } else if (monthFilter.isEmpty() && paiddate[0].equals(yearFilter)) {
                    String paymentInfo = info[9] + "," + info[10] + "," + info[0] + "," + info[1] + "," + info[2] + "," + info[4] + "," + info[5] + "," + info[3];
                    String[] tableData = paymentInfo.split(",");
                    model.addRow(tableData);
                } else if (yearFilter.isEmpty() && paiddate[1].equals(monthFilter)) {
                    String paymentInfo = info[9] + "," + info[10] + "," + info[0] + "," + info[1] + "," + info[2] + "," + info[4] + "," + info[5] + "," + info[3];
                    String[] tableData = paymentInfo.split(",");
                    model.addRow(tableData);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(car_info.class.getName()).log(Level.SEVERE, null, ex);
        }
        getTotal();


    }//GEN-LAST:event_searchBTActionPerformed

    private void printBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBTActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report of total earned");
        MessageFormat footer = new MessageFormat("{0,number,integer}");
        try {
            table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(report_money.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printBTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTActionPerformed

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        new generate_report(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBTActionPerformed

    private void yearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTFActionPerformed

    private void monthTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void report_money(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report_money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report_money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report_money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report_money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report_money().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBT;
    private javax.swing.JLabel mm;
    private javax.swing.JLabel mm1;
    private javax.swing.JTextField monthTF;
    private javax.swing.JButton printBT;
    private javax.swing.JButton returnBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JTable table;
    private javax.swing.JLabel total;
    private javax.swing.JTextField yearTF;
    private javax.swing.JLabel yyyy;
    // End of variables declaration//GEN-END:variables
}
