/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yibei
 */
public class report_systemlog extends javax.swing.JFrame {

    /**
     * Creates new form report_systemlog
     */
    String username;

    public report_systemlog() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    public report_systemlog(String username) {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
        displayTable();
        totalCount();
    }

    public void displayTable() {
        try {
            FileReader file;
            file = new FileReader("systemlog.txt");
            BufferedReader reader = new BufferedReader(file);
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            Object[] tableLines = reader.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] info = line.split(",");
                model.addRow(info);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(report_systemlog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void totalCount() {
        int rowsNum = table.getRowCount();
        String rows = Integer.toString(rowsNum);
        total.setText(rows);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total = new javax.swing.JLabel();
        yyyy = new javax.swing.JLabel();
        mm = new javax.swing.JLabel();
        yearTF = new javax.swing.JTextField();
        monthTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        background = new javax.swing.JLabel();
        printBT = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();
        returnBT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        total.setFont(new java.awt.Font("Elephant", 0, 48)); // NOI18N
        getContentPane().add(total);
        total.setBounds(250, 570, 290, 70);

        yyyy.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        yyyy.setText("YYYY");
        getContentPane().add(yyyy);
        yyyy.setBounds(490, 270, 80, 19);

        mm.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mm.setText("MM");
        getContentPane().add(mm);
        mm.setBounds(330, 270, 50, 19);

        yearTF.setFont(new java.awt.Font("Niagara Engraved", 0, 56)); // NOI18N
        getContentPane().add(yearTF);
        yearTF.setBounds(380, 210, 100, 80);

        monthTF.setFont(new java.awt.Font("Niagara Engraved", 0, 56)); // NOI18N
        getContentPane().add(monthTF);
        monthTF.setBounds(220, 210, 100, 80);

        table.setBackground(new java.awt.Color(204, 164, 98));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Login Status", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 312, 1110, 260);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/report_systemlog.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 768);

        printBT.setText("jButton1");
        printBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBTActionPerformed(evt);
            }
        });
        getContentPane().add(printBT);
        printBT.setBounds(630, 620, 130, 70);

        searchBT.setText("jButton1");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        getContentPane().add(searchBT);
        searchBT.setBounds(100, 210, 110, 80);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(20, 0, 150, 80);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1200, 0, 150, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        String monthFilter = monthTF.getText();
        String yearFilter = yearTF.getText();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        FileReader file;
        model.setRowCount(0);
        try {
            file = new FileReader("systemlog.txt");
            BufferedReader reader = new BufferedReader(file);
            Object[] tableLines = reader.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] info = line.split(",");
                String[] logindate = info[2].split("-");
                if (logindate[1].equals(monthFilter) && logindate[0].equals(yearFilter)) {
                    model.addRow(info);
                } else if (logindate[1].equals(monthFilter) && yearFilter.isEmpty()) {
                    model.addRow(info);
                } else if (logindate[0].equals(yearFilter) && monthFilter.isEmpty()) {
                    model.addRow(info);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(report_systemlog.class.getName()).log(Level.SEVERE, null, ex);
        }
        totalCount();
    }//GEN-LAST:event_searchBTActionPerformed

    private void printBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBTActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("System Log");
       MessageFormat footer = new MessageFormat("{0,number,integer}");
        try {
            table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(report_member.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printBTActionPerformed

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        // TODO add your handling code here:
        new generate_report(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void report_systemlog(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report_systemlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report_systemlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report_systemlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report_systemlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report_systemlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mm;
    private javax.swing.JTextField monthTF;
    private javax.swing.JButton printBT;
    private javax.swing.JButton returnBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JTable table;
    private javax.swing.JLabel total;
    private javax.swing.JTextField yearTF;
    private javax.swing.JLabel yyyy;
    // End of variables declaration//GEN-END:variables
}
