/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Files.readBooking;
import static GUI.Files.readCustomer;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yibei
 */
public class report_carrented extends javax.swing.JFrame {

    /**
     * Creates new form report_carrented
     */
    String username;

    public report_carrented() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }

    public report_carrented(String username) throws IOException {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1366, 796));
        this.username = username;
        displayTable();
        totalCount();

    }

    public void displayTable() throws IOException {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        ArrayList<Booking> list = readBooking();
        for (Booking b : list) {
            if(b.getCarStatus().equals("returned")) {
            String paymentInfo = b.getCarID() + "," + b.getCarPlate() + "," + b.getCarBrand() + "," + b.getCarName() + "," + b.getPickupDate() + ","
                    + b.getDropoffDate() + "," + b.getUsername();
            model.addRow(paymentInfo.split(","));
            }
        }

    }

    public void totalCount() {
        int rowsNum = table.getRowCount();
        String rows = Integer.toString(rowsNum);
        total.setText(rows);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        yyyy = new javax.swing.JLabel();
        mm = new javax.swing.JLabel();
        yearTF = new javax.swing.JTextField();
        monthTF = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        searchBT = new javax.swing.JButton();
        printTF = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        returnBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setBackground(new java.awt.Color(248, 146, 48));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CarID", "Car Plate", "Car Brand", "Car Name", "Pickup Date", "Dropoff Date", "Username"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(72, 262, 1130, 300);

        total.setFont(new java.awt.Font("Elephant", 0, 48)); // NOI18N
        getContentPane().add(total);
        total.setBounds(260, 580, 240, 50);

        yyyy.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        yyyy.setText("YYYY");
        getContentPane().add(yyyy);
        yyyy.setBounds(480, 220, 70, 19);

        mm.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mm.setText("MM");
        getContentPane().add(mm);
        mm.setBounds(310, 220, 50, 19);

        yearTF.setFont(new java.awt.Font("Niagara Engraved", 0, 56)); // NOI18N
        getContentPane().add(yearTF);
        yearTF.setBounds(370, 170, 100, 70);

        monthTF.setFont(new java.awt.Font("Niagara Engraved", 0, 56)); // NOI18N
        getContentPane().add(monthTF);
        monthTF.setBounds(200, 170, 100, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/car_rented.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1366, 768));
        background.setMinimumSize(new java.awt.Dimension(1366, 768));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(background);
        background.setBounds(0, -30, 1370, 830);

        searchBT.setText("jButton1");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        getContentPane().add(searchBT);
        searchBT.setBounds(90, 160, 90, 80);

        printTF.setText("jButton1");
        printTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTFActionPerformed(evt);
            }
        });
        getContentPane().add(printTF);
        printTF.setBounds(560, 640, 150, 60);

        logoutBT.setText("jButton1");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBT);
        logoutBT.setBounds(1190, 20, 140, 60);

        returnBT.setText("jButton1");
        returnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTActionPerformed(evt);
            }
        });
        getContentPane().add(returnBT);
        returnBT.setBounds(40, 10, 150, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        String monthFilter = monthTF.getText();
        String yearFilter = yearTF.getText();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        FileReader file;
        model.setRowCount(0);
        try {
            file = new FileReader("cusbooking.txt");
            BufferedReader reader = new BufferedReader(file);
            Object[] tableLines = reader.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] info = line.split(",");
                String[] bookdate = info[4].split("-");
                if (info[10].equals("returned")) {
                    if (bookdate[1].equals(monthFilter) && bookdate[0].equals(yearFilter)) {
                        String membersInfo = info[0] + "," + info[12] + "," + info[1] + "," + info[2] + "," + info[4] + "," + info[6] + "," + info[11];
                        String[] tableData = membersInfo.split(",");
                        model.addRow(tableData);
                    } else if (bookdate[1].equals(monthFilter) && yearFilter.isEmpty()) {
                        String membersInfo = info[0] + "," + info[12] + "," + info[1] + "," + info[2] + "," + info[4] + "," + info[6] + "," + info[11];
                        String[] tableData = membersInfo.split(",");
                        model.addRow(tableData);
                    } else if (bookdate[0].equals(yearFilter) && monthFilter.isEmpty()) {
                        String membersInfo = info[0] + "," + info[12] + "," + info[1] + "," + info[2] + "," + info[4] + "," + info[6] + "," + info[11];
                        String[] tableData = membersInfo.split(",");
                        model.addRow(tableData);
                    }
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(report_carrented.class.getName()).log(Level.SEVERE, null, ex);
        }
        totalCount();
    }//GEN-LAST:event_searchBTActionPerformed

    private void printTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTFActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report of Car Rented");
        MessageFormat footer = new MessageFormat("{0,number,integer}");
        try {
            table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(report_member.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printTFActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTActionPerformed

    private void returnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTActionPerformed
        // TODO add your handling code here:
        new generate_report(this.username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void report_carrented(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report_carrented.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report_carrented.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report_carrented.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report_carrented.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report_carrented().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBT;
    private javax.swing.JLabel mm;
    private javax.swing.JTextField monthTF;
    private javax.swing.JButton printTF;
    private javax.swing.JButton returnBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JTable table;
    private javax.swing.JLabel total;
    private javax.swing.JTextField yearTF;
    private javax.swing.JLabel yyyy;
    // End of variables declaration//GEN-END:variables
}
