/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;

/**
 *
 * @author Zukrina31
 */
public class Startpage extends javax.swing.JFrame {

    /**
     * Creates new form Startpage
     */
    public Startpage() {
        initComponents();
        //So that the window size is consistent throughout
        setMinimumSize(new java.awt.Dimension(1366, 796));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JLabel();
        Customer_register = new javax.swing.JButton();
        Customer_login = new javax.swing.JButton();
        Admin_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Main Start.png"))); // NOI18N
        Background.setText("jLabel1");
        Background.setMaximumSize(new java.awt.Dimension(1366, 768));
        Background.setMinimumSize(new java.awt.Dimension(1366, 768));
        Background.setPreferredSize(new java.awt.Dimension(1366, 768));
        Background.setSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1366, 768);

        Customer_register.setText("jButton4");
        Customer_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_registerActionPerformed(evt);
            }
        });
        getContentPane().add(Customer_register);
        Customer_register.setBounds(920, 650, 350, 70);

        Customer_login.setText("jButton3");
        Customer_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_loginActionPerformed(evt);
            }
        });
        getContentPane().add(Customer_login);
        Customer_login.setBounds(920, 560, 350, 70);

        Admin_login.setText("jButton1");
        Admin_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_loginActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_login);
        Admin_login.setBounds(919, 464, 350, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Customer_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_registerActionPerformed
//        JOptionPane.showMessageDialog(this, "Register Customer");
        create_acc createAcc = new create_acc();
        this.setVisible(false);
        createAcc.setVisible(true);
    }//GEN-LAST:event_Customer_registerActionPerformed

    private void Admin_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_loginActionPerformed

        //After clicking on the button the page will close and the admin login page will open
        
        this.setVisible(false);
        Admin_login ob = new Admin_login();
        ob.setVisible(true);
    }//GEN-LAST:event_Admin_loginActionPerformed

    private void Customer_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_loginActionPerformed
//        JOptionPane.showMessageDialog(this, "Hello Customer");
        customer_login cusLogin = new customer_login();
        cusLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Customer_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_login;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Customer_login;
    private javax.swing.JButton Customer_register;
    // End of variables declaration//GEN-END:variables
}
